import { ListNode /*, addTwoNumbers*/ } from "./WithoutRecursion.ts";
import { addTwoNumbers } from "./WithRecursion.ts";

// Tests generated by ChatGPT
function runTest(l1Arr: number[], l2Arr: number[]) {
  const l1 = arrayToList(l1Arr);
  const l2 = arrayToList(l2Arr);

  const result = addTwoNumbers(l1, l2);

  console.log("l1:", l1Arr);
  console.log("l2:", l2Arr);
  console.log("result:", listToArray(result));
  console.log("--------------");
}

// ---------- Helpers ----------

// Convert array → linked list
function arrayToList(arr: number[]): ListNode | null {
  let dummy = new ListNode();
  let current = dummy;

  for (const num of arr) {
    current.next = new ListNode(num);
    current = current.next;
  }

  return dummy.next;
}

// Convert linked list → array
function listToArray(head: ListNode | null): number[] {
  const result: number[] = [];
  while (head) {
    result.push(head.val);
    head = head.next;
  }
  return result;
}

// ---------- Test Cases ----------

// Example 1
runTest([2, 4, 3], [5, 6, 4]); // expect [7,0,8]

// Example 2
runTest([0], [0]); // expect [0]

// Example 3
runTest([9, 9, 9, 9, 9, 9, 9], [9, 9, 9, 9]); // expect [8,9,9,9,0,0,0,1]

// Extra edge cases

// Different lengths
runTest([1, 8], [0]); // 81 + 0 → [1,8]

// Carry at end
runTest([5], [5]); // [0,1]

// One very long number
runTest([9, 9, 9], [1]); // [0,0,0,1]

// Random tests
runTest([3, 1, 5], [5, 9, 2]); // 513 + 295 → [8,0,8]
runTest([1], [9, 9, 9]); // [0,0,0,1]
